server:
  port: 10505
spring:
  redis:
    host: 8.130.97.145
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 0
sms:
  ali:
    # 子用户的访问键
    accessKeyId: LTAI5tFhzvktt9U5j4ak2637
    # 子用户的访问密钥
    accessKeySecret: hYLiytNltwB1pOetnBiNcXPmXqfvkx
    # 签名名称
    signName: 逐浪教育
    # 登录短信模板的code
    loginTemplateCode: SMS_275395309